version: "2"

services:
    ungit:
        build:
            context: ./
            dockerfile: Dockerfile
        image: ungit:latest
        ports:
            - "8448:8448"
        volumes:
            # NOTE: POINT THIS TO WHERE THE CODEZ ARE
            - ~/vso:/vso
        
